### ISSUE TITLE
FoundryV11 - Creature Codex Table Not Loading & Encounter Generator making incomplete encounters with errors.

### ISSUE THREAD

**Issue by CobaltKyro** [etriebe/dnd-randomizer#59] opened 2023-07-11 23:50 UTC
Creature Codex Table Not Loading:
![image](https://github.com/etriebe/dnd-randomizer/assets/45078054/0c831b4f-5333-43a5-957e-7df223075dfb)
![image](https://github.com/etriebe/dnd-randomizer/assets/45078054/506805ad-9aee-4b50-936b-3120b04a5a90)

Encounter Generator making incomplete encounters with errors:
![image](https://github.com/etriebe/dnd-randomizer/assets/45078054/f869c8c0-f610-4db0-b245-0df973675dbb)
![image](https://github.com/etriebe/dnd-randomizer/assets/45078054/cf6fd0d3-c120-4525-8a40-2e980e309fcc)

**Comment by etriebe** [comment] 2023-07-14 17:42
For the generating encounters issue, do you have any compeniums with spells inside them? That'll be required.

**Comment by etriebe** [comment] 2023-07-14 18:05
I've made it so this shouldn't break anymore and it'll just say "Spell scroll (X level)" if you don't have spells indexed and have a warning in console indicating you need to index code.

**Comment by etriebe** [comment] 2023-07-14 18:10
Also, creature codex will no longer look at items, unfortunately. This is due to some changes to how we index things, in that we no longer create our own index and rely on the indexing tools Foundry provides. Unfortunately you can't get items (i.e. attacks, features) for a creature with the Foundry index.

**Comment by CobaltKyro** [comment] 2023-07-17 15:54
Hey thanks for looking into this so quickly! So does this mean the the Creature Codex will no longer function at all?

Still appears to be not working:
![image](https://github.com/etriebe/dnd-randomizer/assets/45078054/2b28eae7-2671-4e02-b6d7-bf190c0661b2)
![image](https://github.com/etriebe/dnd-randomizer/assets/45078054/d0c9e764-8de8-46ec-8e31-1d8dfb0d1c18)

Also, the generator is not longer giving me red tier erros, but is giving me those missing index spells warnings. But I do have a spell compendium checked off, so shouldn't it be working? (Also you can see that their are still missing encounters entirely for certain difficulty types):
![image](https://github.com/etriebe/dnd-randomizer/assets/45078054/fbbd253b-3606-4074-a296-c91c5989ee97)
![image](https://github.com/etriebe/dnd-randomizer/assets/45078054/912c3709-6930-4d40-b810-27c0570cfb31)

**Comment by etriebe** [comment] 2023-07-17 19:40
Could you ping me on discord? I might need access to your world to reproduce. :)

**Comment by etriebe** [comment] 2023-07-17 21:18
Fixed in #61 

https://github.com/etriebe/dnd-randomizer/releases/tag/1.0.38

**Closed by etriebe** 2023-07-17 21:18 UTC
