### ISSUE TITLE
Make it clear when encounter generator wasn't able to fill the formula

### ISSUE THREAD

**Issue by Hananack** [etriebe/dnd-randomizer#57] opened 2023-07-07 11:41 UTC
hello
I am Trying to create an encounter in "Stochastic fantastic encounter generator" and I am trying to create lieutenants and lackeys (moderate) encounter i have 5 lvl2 players in group and the generator only generates single 1st lvl lieutenant encounters
I'll appreciate any help.
Thank you
[https://media.discordapp.net/attachments/722566083499786352/1126816605234528319/image.png?width=615&height=700](url)
[https://discord.com/channels/170995199584108546/722566083499786352/1126816605461033030](url)

**Comment by etriebe** [comment] 2023-07-07 17:42
So this is kind of by design for an encounter for 5 level 2's. The design is for 1 at their level and 4 creature 4 levels below theirs. There is no way to find an enemy 4 levels below level 2, so it doesn't make sense. I could make it easier to make this obvious, though so keeping this open. 

        "Lieutenant and Lackeys (Moderate)": { "EncounterFormula": ["1:0", "4:-4"], "EncounterDifficulty": "Moderate" },

**Comment by etriebe** [comment] 2023-07-17 21:17
Fixed in #61 

https://github.com/etriebe/dnd-randomizer/releases/tag/1.0.38

**Closed by etriebe** 2023-07-17 21:17 UTC
